
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Not env(): `prisma generate` runs at build time, before DATABASE_URL is necessarily set
    url: process.env.DATABASE_URL ?? "",
  },
});
